baseURL = "https://example.com"
title = "ShiftLeftCyber"
author = "username"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = false

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logos/marketing_site_logos/main.png"
    alt = "SBOM management solutions by ShiftLeftCyber"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "ShiftLeftCyber.io"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "ShiftLeftCyber helps manage Software Bill of Materials (SBOM) with compliance-focused solutions, enhancing cyber resilience."
    meta_og_title = "ShiftLeftCyber"
    meta_og_type = "website"
    meta_og_url = "https://shiftleftcyber.io"
    meta_og_image = "https://shiftleftcyber.io/img/high-res/metaimage.jpg"
    meta_og_description = "Discover our innovative solutions and read our latest insights on our blog."

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products & Services"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contactOld/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/shiftleftcyber"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
  